# Generated by Django 5.0.3 on 2025-06-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airline_code", models.CharField(max_length=10)),
                ("flight_number", models.CharField(max_length=10)),
                ("departure_date", models.DateField()),
                ("status", models.CharField(max_length=100)),
                ("departure_airport", models.CharField(max_length=100)),
                ("arrival_airport", models.CharField(max_length=100)),
                ("scheduled_departure", models.DateTimeField()),
                ("scheduled_arrival", models.DateTimeField()),
            ],
        ),
    ]
